### GET request to example server
POST localhost:3000/register
Content-Type: application/json

{
  "email": "toto4@gmail.com",
  "password": "1234567"
}
###
POST localhost:3000/login
Content-Type: application/json

{
  "email": "toto4@gmail.com",
  "password": "1234567"
}
####
POST livestream-app-getstream-server-production.up.railway.app/register
Content-Type: application/json

{
  "email": "toto5@gmail.com",
  "password": "1234567"
}

###
POST livestream-app-getstream-server-production.up.railway.app/login
Content-Type: application/json

{
  "email": "toto5@gmail.com",
  "password": "1234567"
}